### ISSUE TITLE
Cannot find package via package control

### ISSUE THREAD

**Issue by Ostendorf** [michaeldyrynda/Laravel.tmTheme#1]
Hi Michael, 

This theme looks great and I would like to try it, but I cannot install/find it via package control.

Software:
* macOS 10.12.6
* Sublime Text 3.0, build 3143

Steps:
1. Shift + Cmd + P
1. Type "Laravel scheme" ("Laravel colour scheme" give 0 results)
1. See only two other *color* schemes, but none with British  *colour* ;-)

**Comment by michaeldyrynda** [comment]
Hey @Ostendorf,

I've submitted the PR to package control to have this added, but it's not been merged in just yet. You'll have to install it manually for the time being. I'll update the README accordingly!
